CREATE CONSTRAINT student_id IF NOT EXISTS
FOR (s:Student)
REQUIRE s.id IS UNIQUE;

CREATE CONSTRAINT course_id IF NOT EXISTS
FOR (c:Course)
REQUIRE c.id IS UNIQUE;

CREATE CONSTRAINT mentor_id IF NOT EXISTS
FOR (m:Mentor)
REQUIRE m.id IS UNIQUE;

CREATE CONSTRAINT skill_id IF NOT EXISTS
FOR (s:Skill)
REQUIRE s.id IS UNIQUE;

CREATE CONSTRAINT project_id IF NOT EXISTS
FOR (p:Project)
REQUIRE p.id IS UNIQUE;

CREATE CONSTRAINT company_id IF NOT EXISTS
FOR (c:Company)
REQUIRE c.id IS UNIQUE;